[theme]
primaryColor        = "#1F497D"
backgroundColor     = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor           = "#262730"
font                = "sans serif"

[server]
maxUploadSize = 50
